### ISSUE TITLE
Floating Tanks

### ISSUE THREAD

**Issue by nikomayra** [quill18/ludum-dare-25#1]
I killed a tank and it got stuck in the air.

![Untitled](https://f.cloud.github.com/assets/3048290/14754/240d1120-4687-11e2-88eb-2185cf07ef8b.png)

the other got stuck after killing it a few times.

![Untitle1d](https://f.cloud.github.com/assets/3048290/14758/69961228-4687-11e2-8697-bd72a8654c78.png)

**Comment by Marcadana** [comment]
Same thing happened to me

**Comment by Stancie** [comment]
Same here. Also had a Issue with one of the tanks (after the first got stuck in the air) stopping at a intersection.
It's also worth to note that you can jump on the turret of the tank and it will spin with you on top at break neck speed.

**Comment by quill18** [comment]
I'll check it out, thanks!
