### ISSUE TITLE
debris cleanup bug

### ISSUE THREAD

**Issue by michael-hardeman** [quill18/ludum-dare-25#11]
The last debris on the level does not get cleaned up.

**Comment by Zbot21** [comment]
Not a bug, I think that there is supposed to be a bit of a "mess" left over after the game is over

**Comment by michael-hardeman** [comment]
You can't have much debris, even on my gaming rig. The "mess" left over is usually 1 building's worth of debris. It looks like a bug more than a feature.

**Comment by Zbot21** [comment]
Shouldn't actually matter in the end since if you destroy everything then the game should end anyways. Still might be something to polish.

**Comment by quill18** [comment]
Won't matter, since the game will end when there are no more buildings anyway.
