### ISSUE TITLE
Tanks: Multiple bugs

### ISSUE THREAD

**Issue by michael-hardeman** [quill18/ludum-dare-25#5]
<h2>Jumping into/onto tank</h2>

If you jump into a tank, or onto one. Strange things happen. One time I was propelled away from the tank at a huge velocity.

<h2>Standing near, or on top of a tank.</h2>

The tank's turret spins wildly around trying to target you.

<h2>Tanks and intersections</h2>

A few tanks stopped at intersections, usually L shaped corner intersections.

**Comment by quill18** [comment]
Turrets no longer turn instantly, solving 1 and 2.

3 was likely fixed by an earlier change.
